#!groovy
node {
    def qmstrbin = "${env.WORKSPACE}/bin"
    def qmstraddress = ""
    def qmstrcachedir = "$HOME/workspace/qmstr-website/qmstrcache"

    try{

        stage('clean')
        {
            cleanWs(deleteDirs: true,
                patterns: [
                    [pattern: 'qmstrcache', type: 'EXCLUDE'],
                    [pattern: 'qmstrcache/**', type: 'EXCLUDE'],
                    [pattern: '.git', type: 'EXCLUDE'],
                    [pattern: '.git/**', type: 'EXCLUDE']
            ])
            sh "ls -laR"
        }
        stage('Clone sources') {
            dir('qmstr') {
                checkout([$class: 'GitSCM',
                    doGenerateSubmoduleConfigurations: false,
                    extensions: [],
                    submoduleCfg: [],
                    branches: [[name: "master"]],
                    userRemoteConfigs: [[url: "https://github.com/QMSTR/qmstr.git"]]])
            }
            dir("qmstr-demo"){
                checkout([$class: 'GitSCM',
                    doGenerateSubmoduleConfigurations: false,
                    extensions: [],
                    submoduleCfg: [],
                    branches: [[name: "master"]],
                    userRemoteConfigs: [[url: "https://github.com/QMSTR/qmstr-demo.git"]]])
            }
            dir("qmstr-demo/demos/java-jabref/jabref"){
                checkout([$class: 'GitSCM',
                    branches: [[name: "master"]],
                    userRemoteConfigs: [[url: 'https://github.com/JabRef/jabref.git']]
                ])
                sh "git clean -fxd"
            }
            dir("web"){
                git poll: false, url: 'https://github.com/qmstr/web'
            }
        }
        stage('Apply qmstr plugin to gradle build configuration') {
            dir("qmstr-demo/demos/java-jabref/jabref"){
                sh 'patch -p1  < ../add-qmstr.patch'
            }
        }
        stage('Compile qmstr') {
            dir("qmstr"){
                sh 'make democontainer'
                sh "mkdir ${qmstrbin}"
                sh "mkdir ${qmstrcachedir} || true"
                def mastername = sh(script: 'docker create qmstr/master', returnStdout: true)
                mastername = mastername.trim()
                sh "docker cp ${mastername}:/usr/local/bin/qmstr ${qmstrbin}/"
                sh "docker cp ${mastername}:/usr/local/bin/qmstrctl ${qmstrbin}/"
                sh "docker rm ${mastername}"
            }
        }
        stage('Build jabref builder image') {
            dir("qmstr-demo"){
                sh 'make java-jabrefdemo EXTRA_BUILD_OPTS=--no-cache'
            }
        }
        stage('Start qmstr-master server') {
            dir("qmstr-demo/demos/java-jabref") {
                sh "sed -i -e '/analysis:/i \\  server: \\n    cachedir: \"${qmstrcachedir}\"' qmstr.yaml"
                sh "sed -i -e 's#localhost:8080#qmstr.org/packages#' qmstr.yaml"
                sh "sed -i -e '/generatehtml/s/# *//' qmstr.yaml"
                sh "cat qmstr.yaml"
                qmstraddress = sh(script: "${qmstrbin}/qmstrctl start --verbose --wait | cut -d \'=\' -f 2", returnStdout: true)
                qmstraddress = qmstraddress.trim()
            }
        }
        stage('Compile jabref with qmstr') {
            dir("qmstr-demo/demos/java-jabref"){
                withEnv(["PATH=${qmstrbin}:${env.PATH}", "QMSTR_MASTER=${qmstraddress}"]) {
                    sh "qmstrctl create package:JabRef && qmstr --container qmstr/java-jabrefdemo ./gradlew qmstr"
                }
            }
        }
        stage('Analysis') {
            withEnv(["PATH=${qmstrbin}:${env.PATH}", "QMSTR_MASTER=${qmstraddress}"]) {
                    sh "qmstrctl analyze --verbose"
            }
        }
        stage('Reporting') {
            withEnv(["PATH=${qmstrbin}:${env.PATH}", "QMSTR_MASTER=${qmstraddress}"]) {
                    sh "qmstrctl report --verbose"
            }
        }
        stage('Shutdown qmstr-master') {
            withEnv(["PATH=${qmstrbin}:${env.PATH}", "QMSTR_MASTER=${qmstraddress}"]) {
                sh "qmstrctl quit"
            }
        }
        stage('Archive artifact')
        {
            archiveArtifacts 'qmstr/qmstr-reporter-html/qmstr-reports.tar.bz2'
        }
        stage('Publish report to website') {
            build job: '/qmstr-website/hugo-website-generation', propagate: false
        }
    }
    catch (Exception e)
    {
        currentBuild.result = 'FAILURE'

        withEnv(["PATH=${qmstrbin}:${env.PATH}", "QMSTR_MASTER=${qmstraddress}"]) {
            echo "########################################"
            echo "######    QMSTR CONTAINER LOGS    ######"
            echo "########################################"
            sh "qmstrctl logs"
            sh "qmstrctl quit"
        }
    }
    finally {
        if (currentBuild.result == 'SUCCESS' && currentBuild.getPreviousBuild().result != 'SUCCESS') {
            googlechatnotification message: "Job ${env.JOB_NAME} ${env.BUILD_NUMBER} successfully finished. See ${env.BUILD_URL}", url: "id:qmstr_hangout_chat_webhook"
        }
        if (currentBuild.result == 'FAILURE') {
            googlechatnotification message: "Job ${env.JOB_NAME} ${env.BUILD_NUMBER} failed. See ${env.BUILD_URL}", url: "id:qmstr_hangout_chat_webhook"
        }
    }
}
