node
{
    try
    {
        parameters {
            string(name: 'qmstrrepo', defaultValue: 'QMSTR', description: 'Repo to use QMSTR or endocode')
            string(name: 'qmstrbranch', defaultValue: 'master', description: 'Branch of qmstr repo to build')
        }
        stage('clean') {
            cleanWs(deleteDirs: true,
                patterns: [
                    [pattern: 'qmstrcache', type: 'EXCLUDE'],
                    [pattern: 'qmstrcache/**', type: 'EXCLUDE'],
                    [pattern: '.git', type: 'EXCLUDE'],
                    [pattern: '.git/**', type: 'EXCLUDE']
            ])
            sh "ls -laR"
        }
        stage('Clone sources') {
            dir('qmstr') {
                checkout([$class: 'GitSCM',
                    doGenerateSubmoduleConfigurations: false,
                    extensions: [],
                    submoduleCfg: [],
                    branches: [[name: "${params.qmstrbranch}"]],
                    userRemoteConfigs: [[url: "https://github.com/${params.qmstrrepo}/qmstr.git"]]])
                sh "git clean -fxd"
            }
        }
        stage('Compile qmstr') {
            dir("qmstr"){
                sh 'make democontainer'
                def mastername = sh(script: 'docker create qmstr/master', returnStdout: true)
                mastername = mastername.trim()
                sh "docker cp ${mastername}:/usr/local/bin/qmstr ../qmstr/out/qmstr"
                sh "docker cp ${mastername}:/usr/local/bin/qmstrctl ../qmstr/out/qmstrctl"
                sh "docker rm ${mastername}"
            }
        }
        stage('Generating docs statics file') {
            dir('qmstr') {
                withEnv(["PATH+SNAP=/snap/bin"]){
                   sh 'cd doc && git submodule init && git submodule update'
                   sh 'make docs'
                }
            }
        }
        stage('Archive artifact') {
            archiveArtifacts 'qmstr/doc/qmstr-doc.tar.bz2'
        }
        stage('Publish report to website') {
            build job: '/QMSTR-intern/web-publisher', propagate: false
        }
    }
    catch (Exception e)
    {
        currentBuild.result = 'FAILURE'
        if (currentBuild.getPreviousBuild().result != 'FAILURE') {
            build job: 'QMSTR-intern/qmstr-notify', parameters: [string(name: 'Message', value:"!!! Job ${env.JOB_NAME} ${env.BUILD_NUMBER} Failed with exception: ${e}. see error at ${env.BUILD_URL}")], propagate: false
        }
    }
}
